// Trac2Speed(Speed, 400);June();
// Turn delay 240 speed 90
void Can1() {
  SL(TurnSpeed);
  delay(240);
  MotorStop();
  FD2(70,70);
  delay(500);
  TracJCStop();
  June();
  BackwardSpeedTime(40, 340);
  MotorStop();
  SR(TurnSpeed);
  delay(225);
  MotorStop();
  BackwardBalance();
  FD2(70,70);
  delay(500);
  TracJCStop();
  June();
  BackwardSpeedTime(40, 340);
  MotorStop();
  SL(TurnSpeed);
  delay(240);
  MotorStop();
  FD2(70,70);
  delay(400);
  TracJCStop();
  June();
  BackwardSpeedTime(40, 340);
  MotorStop();
  SL(TurnSpeed);
  delay(470);
  MotorStop();
  BackwardBalance();
  delay(50);
  // FD2(70,70);
  // delay(500);
  // TracJCStop();
  // June();
  // BackwardSpeedTime(40, 340);
  // MotorStop();

  
  // SR(TurnSpeed);
  // delay(230);
  // MotorStop();
  // BackwardBalance();
  // FD2(70,70);
  // delay(900);
  // ao();
  // TracJCStop();
  // June();
  // BackwardSpeedTime(40, 350);
  // MotorStop();
  // SR(TurnSpeed);
  // delay(235);
  // MotorStop();
  // BackwardBalance();
  // FD2(70,70);
  // delay(850);
  // FD2(40,40);
  // delay(100);
  // MotorStop();
  // delay(50);
  // SR(TurnSpeed);
  // delay(225);
  // MotorStop();
  // BackwardBalance();
  // FD2(70,70);
  // delay(400);
  // TracJCStop(); 
  // June();
  // BackwardSpeedTime(40, 340);
  // MotorStop();
  // SL(TurnSpeed);
  // delay(230);
  // MotorStop();

  // BackwardBalance();

  // FD2(70,70);
  // delay(500);
  // TracJCStop();
  // June();
  // BackwardSpeedTime(40, 340);
  // MotorStop();
  // SR(TurnSpeed);
  // delay(230);
  // MotorStop();
  // FD2(70,70);
  // delay(350);
  // MotorStop();
  // delay(50);
  // SR(TurnSpeed);
  // delay(180);
  // MotorStop();
  // delay(200);
  // FD2(70,70);
  // delay(400);
  // TracJCStop();
  // June();
  // BackwardSpeedTime(40, 360);
  // MotorStop();
  // SL(TurnSpeed);
  // delay(225);
  // MotorStop();
  // FD2(70,70);
  // delay(800);
  // TracJCStop();
  // June();
  // BackwardSpeedTime(40, 360);
  // MotorStop();
  // SL(TurnSpeed);
  // delay(225);
  // MotorStop();

  //------------------------------------------------------------------------------
  // TracJCSonar(12);
  // SR(TurnSpeed);
  // delay(240);
  // MotorStop();
  // TracJCStop();
  // delay(250);
  // June();
  // delay(100);
  // BackwardSpeedTime(40, 450);
  // SL(TurnSpeed);
  // delay(240);
  // MotorStop();
  // Trac2Speed(30, 300);
  // Trac2Speed(70, 500);
  // TracJCSonar(15);
  // SL(TurnSpeed);
  // delay(240);
  // MotorStop();
  // TracJCStop();
  // June();
  // BackwardSpeedTime(40, 250);
  // MotorStop();
  // TurnRightDegree(100,105,2);
  // MotorStop();
  // s4();
  // S5();
  // ao();
  // delay(150);
  // Trac2Speed(40, 180);
  // ao();
  // delay(150);
  // s6();
  // S4();
  // s5();
  //---------------------------------------------------

}