void Show8Analog() {
  oled.clear();
  oled.textSize(1);
  oled.text(0,1,"Black");
  oled.show();
  sw_ok_press();
  beep(1);
  Read4Analog();
  RefL2 = L2;
  RefL1 = L1;
  RefR1 = R1;
  RefR2 = R2;
  oled.text(2,0,"L2=%d",L2);
  oled.text(3,0,"L1=%d",L1);
  oled.text(4,0,"R1=%d",R1);
  oled.text(5,0,"R2=%d",R2);
  oled.text(0,9,"White");
  oled.show();
  sw_ok_press();
  beep(2);
  Read4Analog();
  oled.text(2,8,"L2=%d",L2);
  oled.text(3,8,"L1=%d",L1);
  oled.text(4,8,"R1=%d",R1);
  oled.text(5,8,"R2=%d",R2);
  oled.show();
  sw_ok_press();
  beep(3);
  oled.text(0,14,"Average");
  RefL2 = (RefL2+L2)/2;
  RefL1 = (RefL1+L1)/2;
  RefR1 = (RefR1+R1)/2;
  RefR2 = (RefR2+R2)/2;
  oled.text(2,17,"%d",RefL2);
  oled.text(3,17,"%d",RefL1);
  oled.text(4,17,"%d",RefR1);
  oled.text(5,17,"%d",RefR2);
  oled.show();
  sw_ok_press();
  beep(100);
  oled.clear();
  oled.text(0,0," Black");
  oled.show();
  sw_ok_press();
  beep(0);
  Read4BackAnalog();
  RefBL2 = BL2;
  RefBL1 = BL1;
  RefBR1 = BR1;
  RefBR2 = BR2;
  oled.text(1,0,"BL2=%d",BL2);
  oled.text(2,0,"BL1=%d",BL1);
  oled.text(3,0,"BR1=%d",BR1);
  oled.text(4,0,"BR2=%d",BR2);
  oled.text(0,9,"White");
  oled.show();
  sw_ok_press();
  beep(1);
  Read4BackAnalog();
  oled.text(1,8,"BL2=%d",BL2);
  oled.text(2,8,"BL1=%d",BL1);
  oled.text(3,8,"BR1=%d",BR1);
  oled.text(4,8,"BR2=%d",BR2);
  oled.text(0,14,"Average");
  oled.show();
  sw_ok_press();
  beep(2);
  RefBL2 = (RefBL2+BL2)/2;
  RefBL1 = (RefBL1+BL1)/2;
  RefBR1 = (RefBR1+BR1)/2;
  RefBR2 = (RefBR2+BR2)/2;
  oled.text(1,17,"%d",RefBL2);
  oled.text(2,17,"%d",RefBL1);
  oled.text(3,17,"%d",RefBR1);
  oled.text(4,17,"%d",RefBR2);
  oled.show();
  sw_ok_press();
  beep(2);
}